[package]
name = "riot-rs-bench"
version.workspace = true
authors.workspace = true
license.workspace = true
edition.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
cfg-if = { workspace = true }
defmt = { workspace = true, optional = true }

[target.'cfg(context = "cortex-m")'.dependencies]
cortex-m = { workspace = true }

[target.'cfg(context = "nrf")'.dependencies]
cortex-m = { workspace = true, features = ["critical-section-single-core"] }

[target.'cfg(context = "rp2040")'.dependencies]
embassy-rp = { workspace = true, features = ["critical-section-impl"] }
