[package]
name = "usb-serial"
version = "0.1.0"
authors.workspace = true
license.workspace = true
edition.workspace = true
publish = false

[lints]
workspace = true

[dependencies]
embassy-executor = { workspace = true, default-features = false }
embassy-time = { workspace = true, default-features = false }
ariel-os = { path = "../../src/ariel-os", features = [
  "usb",
  "override-usb-config",
] }
ariel-os-boards = { path = "../../src/ariel-os-boards" }
