[package]
name = "nrf5340"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
license.workspace = true
edition = "2021"

[dependencies]
ariel-os-debug = { workspace = true, features = ["rtt-target"] }

[build-dependencies]
ld-memory = { workspace = true, features = ["build-rs"] }
