name: Bug Report
description: Create a bug report for Ariel OS

body:
  - type: markdown
    attributes:
      value: |
        Thank you for filing a bug report!
  - type: textarea
    attributes:
      label: Summary
      description: Please provide a short summary of the bug, along with any information you feel relevant to replicate the bug.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
    validations:
      required: false
  - type: textarea
    attributes:
      label: Hardware/ Setup
      description: Any relevant information about the used hardware, setup, Ariel OS version, etc.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Possible Solution
      description: Suggest a fix/reason for the bug, or ideas how to implement the addition or change.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Would you like to work on fixing this bug?
      options:
        - "Yes"
        - "No"
        - Maybe
    validations:
      required: true
