name: Feature request
description: Suggest a new feature in Ariel OS
body:
  - type: textarea
    attributes:
      label: Description
      description: Briefly describe the feature that you are requesting.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Motivation
      description: Explain why this feature is needed.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Requirements
      description: Write a list of what you want this feature to do.
      placeholder: "1."
    validations:
      required: true
  - type: textarea
    attributes:
      label: Open questions
      description: Use this section to ask any questions that are related to the feature.
    validations:
      required: false
  - type: dropdown
    attributes:
      label: Are you planning to do it yourself in a pull request?
      options:
        - "Yes"
        - "No"
        - Maybe
    validations:
      required: true
