[package]
name = "riot-rs-runqueue"
version = "0.1.2"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
license.workspace = true
edition = "2018"
description = "RIOT-rs runqueue implementation"

[lints]
workspace = true

[dependencies]
defmt = { workspace = true, optional = true }
