[package]
name = "riot-rs-threads"
version = "0.1.0"
edition = "2021"
authors = [
  "Kaspar Schleiser <kaspar@schleiser.de>",
  "Elena Frank <elena.frank@proton.me>",
]
license.workspace = true
description = "generic embedded scheduler & IPC"
include = ["src/**/*", "README.md"]
repository.workspace = true

[lints]
workspace = true

[dependencies]
cfg-if.workspace = true
critical-section.workspace = true
linkme = { workspace = true }
paste.workspace = true
riot-rs-runqueue.workspace = true
static_cell.workspace = true

defmt = { workspace = true, optional = true }

[target.'cfg(context = "esp32c3")'.dependencies]
esp-hal = { workspace = true, features = ["esp32c3"] }

[target.'cfg(context = "esp32c6")'.dependencies]
esp-hal = { workspace = true, features = ["esp32c6"] }

[target.'cfg(context = "esp32s3")'.dependencies]
esp-hal = { workspace = true, features = ["esp32s3"] }
static_cell = { workspace = true, optional = true }

[target.'cfg(context = "cortex-m")'.dependencies]
# cortex-m specifics
cortex-m.workspace = true
cortex-m-rt.workspace = true
cortex-m-semihosting.workspace = true
panic-semihosting = { version = "0.6.0", features = ["exit"] }

[target.'cfg(context = "rp2040")'.dependencies]
static_cell = { workspace = true, optional = true }
rp-pac = { workspace = true, optional = true }
embassy-rp = { workspace = true, optional = true }

[features]
defmt = ["dep:defmt", "riot-rs-runqueue/defmt"]
multicore = [
  "dep:static_cell",
  "dep:rp-pac",
  "dep:embassy-rp",
  "embassy-rp/fifo-handler",
]
core-affinity = ["multicore"]
