[package]
name = "stm32"
version = "0.1.0"
license.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[target.'cfg(context = "stm32h7b0")'.dependencies]
riot-rs-embassy = { path = "../../riot-rs-embassy" }
riot-rs-rt = { path = "../../riot-rs-rt", features = ["rtt-target"] }
