[package]
name = "rpi-pico"
version = "0.1.0"
license.workspace = true
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ariel-os-debug.workspace = true
ariel-os-rt.workspace = true
rp2040 = { path = "../../ariel-os-chips/rp2040" }

[features]
rpi-pico-w = []
