[package]
name = "ariel-os-arch"
version = "0.1.0"
license.workspace = true
edition = "2021"

[lints]
workspace = true

[dependencies]
cfg-if.workspace = true

[target.'cfg(context = "esp")'.dependencies]
ariel-os-esp = { path = "../ariel-os-esp" }

[target.'cfg(context = "nrf")'.dependencies]
ariel-os-nrf = { path = "../ariel-os-nrf" }

[target.'cfg(context = "rp")'.dependencies]
ariel-os-rp = { path = "../ariel-os-rp" }

[target.'cfg(context = "stm32")'.dependencies]
ariel-os-stm32 = { workspace = true }

# Required for platform-independent tooling
[target.'cfg(not(any(context = "esp", context = "nrf", context = "rp", context = "stm32")))'.dependencies]
embassy-executor = { workspace = true }
embassy-hal-internal = { workspace = true }
embassy-usb = { workspace = true }
embedded-hal = { workspace = true }
embedded-hal-async = { workspace = true }
ariel-os-embassy-common = { workspace = true }

[features]
external-interrupts = [
  "ariel-os-esp/external-interrupts",
  "ariel-os-nrf/external-interrupts",
  "ariel-os-rp/external-interrupts",
  "ariel-os-stm32/external-interrupts",
]

i2c = [
  "ariel-os-esp/i2c",
  "ariel-os-nrf/i2c",
  "ariel-os-rp/i2c",
  "ariel-os-stm32/i2c",
]

spi = [
  "ariel-os-esp/spi",
  "ariel-os-nrf/spi",
  "ariel-os-rp/spi",
  "ariel-os-stm32/spi",
]

usb = [
  #"ariel-os-esp/usb",
  "ariel-os-nrf/usb",
  "ariel-os-rp/usb",
  "ariel-os-stm32/usb",
]

hwrng = [
  #"ariel-os-esp/hwrng",
  "ariel-os-nrf/hwrng",
  "ariel-os-rp/hwrng",
  "ariel-os-stm32/hwrng",
]

wifi-cyw43 = ["ariel-os-rp/wifi-cyw43"]
wifi-esp = ["ariel-os-esp/wifi-esp"]

executor-single-thread = ["ariel-os-esp/executor-single-thread"]

executor-interrupt = [
  #"ariel-os-esp/executor-interrupt",
  "ariel-os-nrf/executor-interrupt",
  "ariel-os-rp/executor-interrupt",
  "ariel-os-stm32/executor-interrupt",
]

defmt = [
  "ariel-os-embassy-common/defmt",
  "ariel-os-esp/defmt",
  "ariel-os-nrf/defmt",
  "ariel-os-rp/defmt",
  "ariel-os-stm32/defmt",
]
