language = "C"
cpp_compat = true
documentation_style = "doxy"
style = "type"
pragma_once = true

includes = ["mutex_t.h", "msg_content.h", "sched_num_threads.h"]

[parse]
parse_deps = true
include = ["ariel-os-runqueue", "ariel-os-threads"]

# Table of name conversions to apply to item names (lhs becomes rhs)
[export.rename]
"ThreadId" = "kernel_pid_t"
"ThreadState" = "thread_state_t"
"ThreadFlags" = "thread_flags_t"
"AtomicBool" = "uint8_t"

[defines]
"feature = core" = "ARIEL_OS_CORE"

[macro_expansion]
# Whether bindings should be generated for instances of the bitflags! macro.
# default: false
bitflags = true

[ptr]
# An optional string to decorate all pointers that are
# required to be non null. Nullability is inferred from the Rust type: `&T`,
# `&mut T` and `NonNull<T>` all require a valid pointer value. 
non_null_attribute = "_Nonnull"
