[package]
name = "threading-multicore"
edition.workspace = true
license.workspace = true
publish = false

[dependencies]
ariel-os = { path = "../../src/ariel-os", features = [] }
ariel-os-boards = { path = "../../src/ariel-os-boards" }
