[package]
name = "microbit"
version = "0.1.0"
authors = ["Kaspar Schleiser <kaspar@schleiser.de>"]
license.workspace = true
edition = "2021"

[dependencies]
cortex-m-rt.workspace = true
cortex-m.workspace = true

riot-rs-debug.workspace = true
riot-rs-rt.workspace = true

nrf51 = { path = "../nrf51" }
